service: addPersonIAM

provider:
  name: aws
  runtime: nodejs16.x
  role: arn:aws:iam::233784350905:role/addPersonAdmin
  region: us-east-1

functions:
  addPerson:
    handler: src/addPerson.handler
    events:
      - http:
          path: /addPersonApp/add
          method: post


  getPeople:
    handler: src/getPeople.handler
    events:
      - http:
          path: /getPeople
          method: get

